#!/bin/bash

set -x
cd $OPENSHIFT_REPO_DIR
export GRADLE_USER_HOME=$OPENSHIFT_DATA_DIR/gradle
export GRADLE_HOME=$OPENSHIFT_DATA_DIR/gradle-2.13
export PATH=$GRADLE_HOME/bin:$PATH

gradle --no-daemon -x test installShadowApp
