#!/bin/bash

# Load DB
tar -Jxvf $OPENSHIFT_REPO_DIR/benchmark/db.txz

mongorestore \
  --host $OPENSHIFT_MONGODB_DB_HOST \
  --port $OPENSHIFT_MONGODB_DB_PORT \
  --db $OPENSHIFT_APP_NAME \
  --username $OPENSHIFT_MONGODB_DB_USERNAME \
  --password $OPENSHIFT_MONGODB_DB_PASSWORD \
  dump/hello_world

rm -rf dump

# Run
export JAVA_HOME=/etc/alternatives/java_sdk_1.8.0
export PATH=$JAVA_HOME/bin:$PATH
export DBHOST=$OPENSHIFT_MONGODB_DB_HOST
$OPENSHIFT_REPO_DIR/build/benchmark_1.0.0/service start
