#!/bin/bash

# Load DB
tar -Jxvf $OPENSHIFT_REPO_DIR/benchmark/db.txz

mongorestore \
  --host $OPENSHIFT_MONGODB_DB_HOST \
  --port $OPENSHIFT_MONGODB_DB_PORT \
  --db $OPENSHIFT_APP_NAME \
  --username $OPENSHIFT_MONGODB_DB_USERNAME \
  --password $OPENSHIFT_MONGODB_DB_PASSWORD \
  dump/

rm -rf dump

# Build
$OPENSHIFT_REPO_DIR/wrapper installShadowApp

# Run
$OPENSHIFT_REPO_DIR/build/benchmark_1.0.0/service start
