#!/usr/bin/env bash

SERVICE_NAME="#{projectName}"
SERVICE_VERSION="#{projectVersion}"
SERVICE_PATH=$(dirname $0)
SERVICE_PID="/tmp/.${SERVICE_NAME}_$SERVICE_VERSION.pid"

log () {
  echo "$SERVICE_NAME ($SERVICE_VERSION) $1"
}

case $1 in
  start)
    if [ ! -f $SERVICE_PID ]; then
      log "starting..."
      nohup $SERVICE_PATH/bin/$SERVICE_NAME "$@" 2>> /dev/null >> /dev/null &
      echo $! > $SERVICE_PID
      log "started"
    else
      log "is already running"
    fi
  ;;
  stop)
    if [ -f $SERVICE_PID ]; then
      log "stopping..."
      PID=$(cat $SERVICE_PID)
      kill $PID
      log "stopped"
      rm $SERVICE_PID
    else
      log "is not running"
    fi
  ;;
  restart)
    $SERVICE_PATH/service stop
    $SERVICE_PATH/service start
  ;;
  status)
    if [ -f $SERVICE_PID ]; then
      log "RUNNING"
    else
      log "STOPPED"
    fi
  ;;
  *)
    echo $"Usage: $0 {start|stop|restart|status}"
    exit 1
  ;;
esac
