package com.hexagontk.http.model

import com.hexagontk.http.model.HttpMethod.GET
import com.hexagontk.http.model.HttpProtocol.HTTP
import com.hexagontk.http.patterns.PathPattern
import java.security.cert.X509Certificate

class HttpRequest(
    override val method: HttpMethod = GET,
    override val protocol: HttpProtocol = HTTP,
    override val host: String = "localhost",
    override val port: Int = 80,
    override val path: String = "",
    override val queryParameters: Parameters = Parameters(),
    override val headers: Headers = Headers(),
    override val body: Any = "",
    override val parts: List<HttpPart> = emptyList(),
    override val formParameters: Parameters = Parameters(),
    override val cookies: List<Cookie> = emptyList(),
    override val contentType: ContentType? = null,
    override val certificateChain: List<X509Certificate> = emptyList(),
    override val accept: List<ContentType> = emptyList(),
    override val contentLength: Long = -1L,
    override val authorization: Authorization? = null,
    override val pathPattern: PathPattern? = null,
    override val pathParameters: Map<String, Any> = emptyMap(),
) : HttpRequestPort {

    constructor(
        pathPattern: PathPattern,
        pathParameters: Map<String, Any>,
        method: HttpMethod = GET,
        protocol: HttpProtocol = HTTP,
        host: String = "localhost",
        port: Int = 80,
        queryParameters: Parameters = Parameters(),
        headers: Headers = Headers(),
        body: Any = "",
        parts: List<HttpPart> = emptyList(),
        formParameters: Parameters = Parameters(),
        cookies: List<Cookie> = emptyList(),
        contentType: ContentType? = null,
        certificateChain: List<X509Certificate> = emptyList(),
        accept: List<ContentType> = emptyList(),
        contentLength: Long = -1L,
        authorization: Authorization? = null,
    ) : this(
        method,
        protocol,
        host,
        port,
        pathPattern.insertParameters(pathParameters),
        queryParameters,
        headers,
        body,
        parts,
        formParameters,
        cookies,
        contentType,
        certificateChain,
        accept,
        contentLength,
        authorization,
        pathPattern,
        pathParameters,
    )

    override fun with(
        body: Any,
        headers: Headers,
        contentType: ContentType?,
        method: HttpMethod,
        protocol: HttpProtocol,
        host: String,
        port: Int,
        path: String,
        queryParameters: Parameters,
        parts: List<HttpPart>,
        formParameters: Parameters,
        cookies: List<Cookie>,
        accept: List<ContentType>,
        authorization: Authorization?,
        certificateChain: List<X509Certificate>,
        pathPattern: PathPattern?,
        pathParameters: Map<String, Any>,
    ): HttpRequestPort =
        HttpRequest(
            body = body,
            headers = headers,
            contentType = contentType,
            method = method,
            protocol = protocol,
            host = host,
            port = port,
            path = path,
            queryParameters = queryParameters,
            parts = parts,
            formParameters = formParameters,
            cookies = cookies,
            accept = accept,
            authorization = authorization,
            certificateChain = certificateChain,
            pathPattern = pathPattern,
            pathParameters = pathParameters,
        )
}
