
#
# This action *WILL REQUIRE* to do the checkout before (as it is used from the same repository).
#
name: Gradle
description: Run a Gradle build executing the supplied tasks.

inputs:
  java:
    description: Java version used to run Gradle.
    required: true
    default: "11"

  java_distribution:
    description: Java distribution used to run Gradle.
    required: true
    default: temurin

  tasks:
    description: Gradle tasks to execute.
    required: true
    default: build

runs:
  using: composite
  steps:

    # SET UP
    - uses: actions/setup-java@v3
      with:
        java-version: ${{ inputs.java }}
        distribution: ${{ inputs.java_distribution }}
        cache: gradle

    # PROCESS
    - run: ./gradlew ${{ inputs.tasks }}
      shell: bash
    - if: failure()
      run: ./gradlew --info --stacktrace ${{ inputs.tasks }}
      shell: bash
