
name: ImageMagick
description: Install ImageMagick 7 (GitHub runners have ImageMagick 6).

runs:
  using: composite
  steps:
    - uses: actions/cache@v3
      with:
        key: ${{ runner.os }}-imagemagick-${{ hashFiles('assets/*.gradle*') }}
        restore-keys: ${{ runner.os }}-imagemagick-
        path: ~/.local/bin/magick
    - name: Install ImageMagick
      shell: bash
      run: |
        sudo apt-get install librsvg2-bin --appimage-extract
        mkdir -p ~/.local/bin
        export MAGICK="https://download.imagemagick.org/ImageMagick/download/binaries/magick"
        [[ ! -f ~/.local/bin/magick ]] && sudo curl "$MAGICK" -o ~/.local/bin/magick
        sudo chmod +x ~/.local/bin/magick
        magick --version
