#!/usr/bin/env bash

alias hx='cd ~/Projects/hexagon'

alias hxloc='hx && gw publishLocal'
alias hxall='hx && gw clean site install libraries installAllTemplates'

alias hxrel='hx && gw clean release'
