
on:
  workflow_call:
    inputs:
      ref:
        type: string
        description: Branch to check out.
        default: ''

      version:
        type: string
        description: GraalVM version used to run Gradle.
        default: latest

      distribution:
        type: string
        description: GraalVM distribution used to run Gradle.
        default: graalvm-community

      java:
        type: string
        description: Java version used to run Gradle.
        default: 21

      check_directory:
        type: string
        description: Directory to check for build execution.
        default: site/build/site

      options:
        type: string
        description: Extra options for the 'buildSite' target.
        default: ''

jobs:
  site:
    runs-on: ubuntu-latest
    defaults:
      run: { shell: bash }
    steps:
      - uses: actions/cache@v4
        with:
          key: ${{ runner.os }}-mkdocs-${{ hashFiles('**/*.gradle*', '**/gradle*.properties') }}
          restore-keys: ${{ runner.os }}-mkdocs-
          path: |
            ~/.local/bin
            ~/.local/lib/python*/site-packages

      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}

      - uses: graalvm/setup-graalvm@v1
        with:
          version: ${{ inputs.version }}
          distribution: ${{ inputs.distribution }}
          java-version: ${{ inputs.java }}
          cache: gradle

      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          export GIT_COMMITTER_NAME="${GITHUB_ACTOR}"
          export GIT_COMMITTER_EMAIL="project@hexagontk.com"
          git fetch origin gh-pages --depth=1
          ./gradlew --stacktrace build
          ./gradlew --stacktrace -x build buildSite ${{ inputs.options }}

      - if: ${{ inputs.check_directory != '' }}
        run: ls -AlF "${{ inputs.check_directory }}"
